name: qsspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.2
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - seaborn=0.13.1
  - statsmodels=0.14.1
  - nltk=3.8.1
  - wordcloud=1.9.2
  - python-igraph=0.11.3
  - geopandas=0.14.2
  - jupyter
